name: Terraform Cloud Workspace
description: Manages Terraform Cloud workspaces
inputs:
  terraform_version:
    description: Terraform version
    default: "1.0.3"
  terraform_token:
    description: Terraform Cloud token
    required: true
  terraform_host:
    description: Terraform Cloud host
    default: app.terraform.io
  terraform_organization:
    description: Terraform Cloud organization
    required: true
  name:
    description: Name of the workspace. Becomes a prefix if workspaces are passed (`${name}-${workspace}`)
    default: "${{ github.event.repository.name }}"
  runner_terraform_version:
    description: Terraform version used to create the workspace
    default: "1.0.3"
  workspaces:
    description: Comma separated list of workspaces
    default: ""
  backend_config:
    description: Backend config block
    default: ""
  apply:
    description: Whether to apply the proposed Terraform changes
    required: true
outputs:
  plan:
    description: Human readable Terraform plan
  plan_json:
    description: JSON plan
runs:
  using: docker
  image: Dockerfile