name: Documentation
on:
  pull_request:
    paths:
      - .githhub/workflows/docs.yml
      - README.md
      - action.yml
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npalm/action-docs-action@v1.2.0
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README from `action.yml`
