name: Documentation
on:
  pull_request:
    paths:
      - .githhub/workflows/docs.yml
      - README.md
      - action.yml
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npalm/action-docs-action@v1.2.0
      - name: Verify documentation is up to date
        run: git diff --exit-code
