name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        env:
          TF_TOKEN: ${{ secrets.TF_TOKEN_OSS }}
          TF_ORGANIZATION: takescoop-oss
        run: go test -v ./...
      - name: Timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"
      - name: E2E test
        uses: ./
        with:
          terraform_organization: takescoop-oss
          terraform_token: ${{ secrets.TF_TOKEN_OSS }}
          name: "action-e2e-test-${{ steps.timestamp.outputs.timestamp }}"
          tags: |-
            - terraform:true
          workspace_tags: |-
            staging:
              - environment:staging
            production:
              - environment:production
          apply: false
          variables: |-
            - key: foo
              value: bar
              category: terraform
          workspace_variables: |-
            staging:
              - key: environment
                value: staging
                category: terraform
              - key: environment
                value: production
                category: terraform
          workspaces: |-
            - staging
            - production
          vcs_type: github


